# Generated by Django 5.0.6 on 2024-07-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='pname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.AddField(
            model_name='product',
            name='pimg',
            field=models.ImageField(default='', upload_to='picture/pimg'),
        ),
    ]
